services:
  web:
    image: ghcr.io/f-a-k-u/itica-web:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ghcr.io/f-a-k-u/itica-backend:latest
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: itica_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge