services:
  web:
    image: ghcr.io/f-a-k-u/itica-web:latest
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    image: ghcr.io/f-a-k-u/itica-backend:latest
    ports:
      - "3001:3001"
    restart: always